In [2]:
import findspark

In [3]:
findspark.init()

In [4]:
import pyspark

In [5]:
sc = pyspark.SparkContext(master='spark://huyang:7077',appName = "LDA")

In [89]:
data = sc.textFile("file:///opt/train.txt")

In [90]:
data.flatMap(lambda x : x.split(" ")).distinct().saveAsTextFile("./python/V")

In [13]:
M = data.map(lambda x : len(x.split(" "))).collect()

In [15]:
len(M)

10060

In [6]:
import numpy as np
import pandas as pd
from numpy import random
from pyspark.sql.types import ShortType
from pyspark.sql.types import FloatType
from pyspark.sql.session import SparkSession
from pyspark.sql.types import StructType
from pyspark.sql.types import StructField
from pyspark.sql.types import StringType
spark=SparkSession.builder.getOrCreate()

In [90]:
df = pd.DataFrame(random.randint(0, 1,(26171,8)))

In [86]:
df

       0  1  2  3  4  5  6  7
0      0  0  0  0  0  0  0  0
1      0  0  0  0  0  0  0  0
2      0  0  0  0  0  0  0  0
3      0  0  0  0  0  0  0  0
4      0  0  0  0  0  0  0  0
5      0  0  0  0  0  0  0  0
6      0  0  0  0  0  0  0  0
7      0  0  0  0  0  0  0  0
8      0  0  0  0  0  0  0  0
9      0  0  0  0  0  0  0  0
10     0  0  0  0  0  0  0  0
11     0  0  0  0  0  0  0  0
12     0  0  0  0  0  0  0  0
13     0  0  0  0  0  0  0  0
14     0  0  0  0  0  0  0  0
15     0  0  0  0  0  0  0  0
16     0  0  0  0  0  0  0  0
17     0  0  0  0  0  0  0  0
18     0  0  0  0  0  0  0  0
19     0  0  0  0  0  0  0  0
20     0  0  0  0  0  0  0  0
21     0  0  0  0  0  0  0  0
22     0  0  0  0  0  0  0  0
23     0  0  0  0  0  0  0  0
24     0  0  0  0  0  0  0  0
25     0  0  0  0  0  0  0  0
26     0  0  0  0  0  0  0  0
27     0  0  0  0  0  0  0  0
28     0  0  0  0  0  0  0  0
29     0  0  0  0  0  0  0  0
...   .. .. .. .. .. .. .. ..
10030  0  0  0  0  0  0  0  0
10031  0  0  0  0  0  0  0  0
10032  0  0  0  0  0  0  0  0
10033  0  0  0  0  0  0  0  0
10034  0  0  0  0  0  0  0  0
10035  0  0  0  0  0  0  0  0
10036  0  0  0  0  0  0  0  0
10037  0  0  0  0  0  0  0  0
10038  0  0  0  0  0  0  0  0
10039  0  0  0  0  0  0  0  0
10040  0  0  0  0  0  0  0  0
10041  0  0  0  0  0  0  0  0
10042  0  0  0  0  0  0  0  0
10043  0  0  0  0  0  0  0  0
10044  0  0  0  0  0  0  0  0
10045  0  0  0  0  0  0  0  0
10046  0  0  0  0  0  0  0  0
10047  0  0  0  0  0  0  0  0
10048  0  0  0  0  0  0  0  0
10049  0  0  0  0  0  0  0  0
10050  0  0  0  0  0  0  0  0
10051  0  0  0  0  0  0  0  0
10052  0  0  0  0  0  0  0  0
10053  0  0  0  0  0  0  0  0
10054  0  0  0  0  0  0  0  0
10055  0  0  0  0  0  0  0  0
10056  0  0  0  0  0  0  0  0
10057  0  0  0  0  0  0  0  0
10058  0  0  0  0  0  0  0  0
10059  0  0  0  0  0  0  0  0

[10060 rows x 8 columns]

In [51]:
sdf = spark.createDataFrame(df)

In [52]:
sdf.write.csv("./python/topicWord")

In [10]:
topicWord = sc.textFile("./python/topicWord")

In [11]:
topicWord = topicWord.collect()

In [53]:
df = pd.DataFrame(random.randint(0, 1,(10060,8)))

In [54]:
sdf = spark.createDataFrame(df)

In [55]:
sdf.write.csv("./python/docTopic")

In [17]:
docTopic = sc.textFile("./python/docTopic")

In [14]:
docTopic = docTopic.collect()

In [28]:
data.map(lambda x : len(x.split(" "))).max()

39

In [ ]:
def f(x) :
    count = len(x.split(" "))
    words = x.split(" ")
    list1 = []
    for i in range(39) :
        if i < len(words) :
            try :
                index = V.index(words[i].encode('utf-8'))
            except Exception, e:
                index = 0
            list1.append(str(index)+"*"+str(random.randint(0, 8)))
        else :
            list1.append(None)
    return list1
data.map(f).saveAsTextFile("./python/normZ")

In [7]:
z = sc.textFile("./python/normZ")

In [8]:
list1 = []
for i in range(39) :
    list1.append(StructField(str(i), StringType(), True))
schema = StructType(list1)
def f(x):
    list1 = []
    words = x.split(",")
    for i in range(len(words)) :
        list1.append(words[i].strip().strip(']').strip('['))
    return list1
df_z = spark.createDataFrame(z.map(f).collect(), schema)

In [9]:
pandas_z = df_z.toPandas()
pandas_z.head(5)

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,'5678*5','22151*5','3291*3','3291*0','75*4','5570*1','5858*2','13965*0','11392*1','5570*3',...,None,None,None,None,None,None,None,None,None,None
1,'14255*3','3353*5','17330*4','22620*2','1676*2','3353*1','17330*0','22620*6','7291*7','21358*2',...,None,None,None,None,None,None,None,None,None,None
2,'4548*2','16432*3','19519*6','4084*5','24839*2','4924*7','5678*4','4300*6','11633*3','17114*1',...,None,None,None,None,None,None,None,None,None,None
3,'12951*5','12951*0','23492*2','23126*7','10295*7','13506*1','13270*1','1017*3','9894*4','19955*3',...,None,None,None,None,None,None,None,None,None,None
4,'25170*0','5858*5','3132*4','5858*4','15141*0','17330*6','4300*1','13463*6','11633*0','20082*1',...,None,None,None,None,None,None,None,None,None,None

In [10]:
V = sc.textFile("./python/V")
V = V.collect()

In [18]:
docTopic = sc.textFile("./python/docTopic")
list1 = []
for i in range(8) :
    list1.append(StructField(str(i), FloatType(), True))
schema = StructType(list1)
def f(x):
    list1 = []
    words = x.split(",")
    for i in range(len(words)) :
        list1.append(float(words[i].strip().strip(']').strip('[')))
    return list1
pandas_docTopic = spark.createDataFrame(docTopic.map(f).collect(), schema).toPandas()

In [19]:
topicWord = sc.textFile("./python/topicWord")
list1 = []
for i in range(8) :
    list1.append(StructField(str(i), FloatType(), True))
schema = StructType(list1)
def f(x):
    list1 = []
    words = x.split(",")
    for i in range(len(words)) :
        list1.append(float(words[i].strip().strip(']').strip('[')))
    return list1
pandas_topicWord = spark.createDataFrame(topicWord.map(f).collect(), schema).toPandas()

In [92]:
pandas_topicWord = pandas_topicWord.astype(float)

In [93]:
pandas_docTopic = pandas_docTopic.astype(float)

In [94]:
for i in range(pandas_z.iloc[:,0].size) :
    if i % 100 == 0 :
        print(i)
    for j in range(pandas_z.columns.size) :
        if pandas_z.ix[i,j] != u'None' :
            words = str(pandas_z.ix[i,j]).strip("'").split("*")
            topic = int(words[1])
            index = int(words[0])
            pandas_docTopic.ix[i,topic] = pandas_docTopic.ix[i,topic]+1
            pandas_topicWord.ix[index,topic] = pandas_topicWord.ix[index,topic]+1
        else :
            break

0

/usr/lib/python2.7/site-packages/ipykernel_launcher.py:5: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """
/usr/lib/python2.7/site-packages/ipykernel_launcher.py:9: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  if __name__ == '__main__':
/usr/lib/python2.7/site-packages/ipykernel_launcher.py:10: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  # Remove the CWD from sys.path while we load stuff.

100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000

In [28]:
spark.createDataFrame(pandas_topicWord).write.csv("./python/topicWord",mode = "overwrite")

In [29]:
spark.createDataFrame(pandas_docTopic).write.csv("./python/docTopic",mode = "overwrite")

In [20]:
pandas_topicWord.sum()

0    23691.0
1    23626.0
2    23670.0
3    23423.0
4    23868.0
5    23933.0
6    23901.0
7    23675.0
dtype: float64

In [24]:
for it in range(10):
    for i in range(pandas_z.iloc[:,0].size) :
        if i % 100 == 0 :
            print(i)
        for j in range(pandas_z.columns.size) :
            if pandas_z.ix[i,j] != u'None' :
                words = str(pandas_z.ix[i,j]).strip("'").split("*")
                oldTopic = int(words[1])
                index = int(words[0])
                pandas_docTopic.ix[i,oldTopic] = pandas_docTopic.ix[i,oldTopic] - 1
                pandas_topicWord.ix[index,oldTopic] = pandas_topicWord.ix[index,oldTopic] - 1
                
                p = (pandas_docTopic.ix[i] + 6.25)/(pandas_docTopic.ix[i].sum()+50)*(pandas_topicWord.ix[index]+0.01)/(pandas_topicWord.sum()+261.71)
                
                new_p = []
                for k in range(8) :
                    new_p.append(sum(p[0:k+1]))
                u = random.random() * new_p[7]
                newTopic = 0
                for newTopic in range(8) :
                    if u < new_p[newTopic] :
                        break
                pandas_docTopic.ix[i,newTopic] = pandas_docTopic.ix[i,newTopic] + 1
                pandas_topicWord.ix[index,newTopic] = pandas_topicWord.ix[index,newTopic] + 1
                pandas_z.ix[i,j] = str(index)+"*"+str(newTopic)
            else :
                break

0

/usr/lib/python2.7/site-packages/ipykernel_launcher.py:11: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  # This is added back by InteractiveShellApp.init_path()

100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000

In [83]:
result = (pandas_topicWord + 0.01)/(pandas_topicWord.sum()+26171*0.01)

In [42]:
result.head()

,0,1,2,3,4,5,6,7
0,7.524397e-03,4.203145e-07,6.144913e-04,2.518046e-04,4.226700e-05,6.248514e-04,7.414968e-04,8.361641e-04
1,4.226952e-07,4.203145e-07,4.093879e-07,4.189761e-07,1.259640e-04,4.162901e-07,4.117139e-07,4.178731e-07
2,4.226952e-07,4.203145e-07,4.093879e-07,4.189761e-07,4.184852e-07,4.204530e-05,4.117139e-07,4.178731e-07
3,4.226952e-07,4.245176e-05,4.093879e-07,4.189761e-07,4.184852e-07,4.162901e-07,4.117139e-07,4.178731e-07
4,4.226952e-07,4.203145e-07,4.093879e-07,4.189761e-07,4.184852e-07,4.162901e-07,4.158311e-05,4.178731e-07

In [43]:
result.insert(0, 'index', result.index)

In [84]:
result.head()

,0,1,2,3,4,5,6,7
0,7.524397e-03,4.203145e-07,6.144913e-04,2.518046e-04,4.226700e-05,6.248514e-04,7.414968e-04,8.361641e-04
1,4.226952e-07,4.203145e-07,4.093879e-07,4.189761e-07,1.259640e-04,4.162901e-07,4.117139e-07,4.178731e-07
2,4.226952e-07,4.203145e-07,4.093879e-07,4.189761e-07,4.184852e-07,4.204530e-05,4.117139e-07,4.178731e-07
3,4.226952e-07,4.245176e-05,4.093879e-07,4.189761e-07,4.184852e-07,4.162901e-07,4.117139e-07,4.178731e-07
4,4.226952e-07,4.203145e-07,4.093879e-07,4.189761e-07,4.184852e-07,4.162901e-07,4.158311e-05,4.178731e-07

In [91]:
for i in range(8) :
    ind = result.sort_values(by = [str(i).decode("utf-8")],ascending = False)[0:10].index
    print("")
    print "topic"+str(i),
    for j in range(10) :
        print V[ind[j]],

topic0 edu computers education-science business research sports khuish health web news
topic1 business culture politics-society trade international wikipedia culture-arts-entertainment directory wiki education-science
topic2 wikipedia health music culture-arts-entertainment education-science encyclopedia science computers research news
topic3 business culture-arts-entertainment politics-society news information education-science com edu wikipedia movie
topic4 com health games culture-arts-entertainment sports amazon education-science research news online
topic5 science culture-arts-entertainment news information business political health education-science research jobs
topic6 sports education-science business research culture-arts-entertainment film democracy theory com football
topic7 education-science com business computers sports news web culture-arts-entertainment law edu